const NAIF = 'https://naif.jpl.nasa.gov/pub/naif';

export const KERNEL_CATALOG = [
  {
    id: 'generic-lsk-naif0012',
    name: 'NAIF leapseconds 0012',
    type: 'LSK',
    role: 'leapseconds',
    url: `${NAIF}/generic_kernels/lsk/naif0012.tls`,
    localPath: 'generic/lsk/naif0012.tls',
    source: 'NAIF generic kernels',
    coverage: { start: '1962-01-01T00:00:00Z', stop: '2100-01-01T00:00:00Z' },
    priority: 100,
    notes: 'Current fixed catalog entry for time conversion examples.',
  },
  {
    id: 'generic-pck-pck00011',
    name: 'IAU body constants pck00011',
    type: 'PCK',
    role: 'body-constants',
    url: `${NAIF}/generic_kernels/pck/pck00011.tpc`,
    localPath: 'generic/pck/pck00011.tpc',
    source: 'NAIF generic kernels',
    coverage: { start: '1900-01-01T00:00:00Z', stop: '2100-01-01T00:00:00Z' },
    bodies: ['MERCURY', 'VENUS', 'EARTH', 'MOON', 'MARS', 'JUPITER', 'SATURN'],
    priority: 100,
  },
  {
    id: 'generic-spk-de442s',
    name: 'DE442s planetary ephemeris',
    type: 'SPK',
    role: 'planetary-ephemeris',
    url: `${NAIF}/generic_kernels/spk/planets/de442s.bsp`,
    localPath: 'generic/spk/planets/de442s.bsp',
    source: 'NAIF generic planetary SPK directory',
    coverage: { start: '1849-12-25T23:59:18.816Z', stop: '2150-01-21T23:58:50.816Z' },
    bodies: ['SUN', 'MERCURY', 'VENUS', 'EARTH', 'MOON', 'MARS BARYCENTER', 'JUPITER BARYCENTER', 'SATURN BARYCENTER'],
    sizeMb: 31,
    priority: 100,
  },
  {
    id: 'generic-spk-jup388s',
    name: 'Jupiter satellite ephemeris jup388s',
    type: 'SPK',
    role: 'jupiter-system',
    url: `${NAIF}/JUNO/kernels/spk/jup388s.bsp`,
    localPath: 'juno/spk/jup388s.bsp',
    source: 'Juno mission SPK directory',
    coverage: { start: '2020-12-31T23:58:50.816Z', stop: '2040-01-07T23:58:50.816Z' },
    bodies: ['JUPITER', 'IO', 'EUROPA', 'GANYMEDE', 'CALLISTO'],
    sizeMb: 34,
    priority: 90,
  },
  {
    id: 'generic-spk-sat441',
    name: 'Saturn satellite ephemeris sat441',
    type: 'SPK',
    role: 'saturn-system',
    url: `${NAIF}/generic_kernels/spk/satellites/sat441.bsp`,
    localPath: 'generic/spk/satellites/sat441.bsp',
    source: 'NAIF generic satellite SPK directory',
    coverage: { start: '1749-12-29T23:59:18.816Z', stop: '2250-01-05T23:58:50.816Z' },
    bodies: ['SATURN', 'MIMAS', 'ENCELADUS', 'TETHYS', 'DIONE', 'RHEA', 'TITAN', 'IAPETUS'],
    sizeMb: 631,
    priority: 90,
  },
  {
    id: 'mro-spk-mar097',
    name: 'Mars system ephemeris mar097',
    type: 'SPK',
    role: 'mars-system',
    url: `${NAIF}/MRO/kernels/spk/spk_mar097_050810_531009_p_v1.bsp`,
    localPath: 'mro/spk/spk_mar097_050810_531009_p_v1.bsp',
    source: 'MRO mission SPK directory',
    coverage: { start: '2005-08-09T23:58:55.817Z', stop: '2053-10-08T23:58:50.818Z' },
    bodies: ['MARS', 'PHOBOS', 'DEIMOS'],
    sizeMb: 106,
    priority: 95,
  },
  {
    id: 'juno-spk-rec-orbit',
    name: 'Juno reconstructed orbit',
    type: 'SPK',
    role: 'spacecraft-trajectory',
    url: `${NAIF}/JUNO/kernels/spk/juno_rec_orbit.bsp`,
    localPath: 'juno/spk/juno_rec_orbit.bsp',
    source: 'Juno mission SPK directory',
    coverage: { start: '2016-07-05T03:47:31.000Z', stop: '2026-04-16T07:03:50.814Z' },
    bodies: ['JUNO'],
    sizeMb: 134,
    priority: 100,
    notes: 'Use with the predicted orbit for requests after reconstructed coverage.',
  },
  {
    id: 'juno-spk-pred-orbit',
    name: 'Juno predicted orbit',
    type: 'SPK',
    role: 'spacecraft-trajectory',
    url: `${NAIF}/JUNO/kernels/spk/juno_pred_orbit.bsp`,
    localPath: 'juno/spk/juno_pred_orbit.bsp',
    source: 'Juno mission SPK directory',
    coverage: { start: '2016-07-05T03:47:31.000Z', stop: '2026-06-07T18:52:33.826Z' },
    bodies: ['JUNO'],
    sizeMb: 31,
    priority: 80,
  },
  {
    id: 'mro-spk-psp-rec',
    name: 'MRO reconstructed orbit current arc',
    type: 'SPK',
    role: 'spacecraft-trajectory',
    url: `${NAIF}/MRO/kernels/spk/mro_psp_rec.bsp`,
    localPath: 'mro/spk/mro_psp_rec.bsp',
    source: 'MRO mission SPK directory',
    coverage: { start: '2026-04-01T00:00:00.814Z', stop: '2026-05-17T08:15:50.815Z' },
    bodies: ['MRO'],
    sizeMb: 74,
    priority: 100,
  },
  {
    id: 'mro-spk-psp',
    name: 'MRO merged orbit current arc',
    type: 'SPK',
    role: 'spacecraft-trajectory',
    url: `${NAIF}/MRO/kernels/spk/mro_psp.bsp`,
    localPath: 'mro/spk/mro_psp.bsp',
    source: 'MRO mission SPK directory',
    coverage: { start: '2026-04-01T00:00:00.814Z', stop: '2026-06-15T13:45:50.815Z' },
    bodies: ['MRO'],
    sizeMb: 95,
    priority: 90,
  },
  {
    id: 'cassini-spk-2012-enceladus',
    name: 'Cassini reconstructed Saturn tour segment 2012-280/328',
    type: 'SPK',
    role: 'spacecraft-trajectory',
    url: `${NAIF}/CASSINI/kernels/spk/200128RU_SCPSE_12280_12328.bsp`,
    localPath: 'cassini/spk/200128RU_SCPSE_12280_12328.bsp',
    source: 'Cassini mission SPK directory',
    coverage: { start: '2012-10-06T11:58:52.818Z', stop: '2012-11-23T07:58:53.817Z' },
    bodies: ['CASSINI', 'SATURN', 'ENCELADUS'],
    priority: 100,
    notes: 'Reconstructed segment useful for the October 2012 Enceladus flyby window.',
  },
];

export const SCENARIOS = [
  {
    id: 'earth-moon-sun',
    name: 'Earth Moon Sun geometry',
    mission: 'Generic NAIF',
    observer: 'EARTH',
    target: 'MOON',
    center: 'EARTH',
    frame: 'J2000',
    abcorr: 'LT+S',
    sampleWindow: { start: '2026-05-20T00:00:00Z', stop: '2026-05-21T00:00:00Z' },
    description: 'A compact generic scenario for lunar state vectors, phase angle, and sub-point recipes.',
    requiredRoles: ['leapseconds', 'body-constants', 'planetary-ephemeris'],
    optionalRoles: [],
    calculations: ['state-vector', 'range-rate', 'phase-angle', 'sub-observer-point', 'sub-solar-point'],
    tags: ['generic', 'teaching', 'small-download'],
  },
  {
    id: 'juno-jupiter',
    name: 'Juno at Jupiter',
    mission: 'Juno',
    observer: 'JUNO',
    target: 'JUPITER',
    center: 'JUPITER',
    frame: 'J2000',
    abcorr: 'LT+S',
    sampleWindow: { start: '2026-03-10T00:00:00Z', stop: '2026-03-11T00:00:00Z' },
    description: 'Juno spacecraft geometry against Jupiter using reconstructed and predicted mission SPKs.',
    requiredRoles: ['leapseconds', 'body-constants', 'planetary-ephemeris', 'jupiter-system', 'spacecraft-trajectory'],
    optionalRoles: ['spacecraft-structure', 'frame-definition', 'spacecraft-clock', 'attitude'],
    calculations: ['state-vector', 'range-rate', 'phase-angle', 'sub-observer-point', 'sub-solar-point'],
    tags: ['mission', 'jupiter', 'active'],
  },
  {
    id: 'mro-mars',
    name: 'Mars Reconnaissance Orbiter at Mars',
    mission: 'Mars Reconnaissance Orbiter',
    observer: 'MRO',
    target: 'MARS',
    center: 'MARS',
    frame: 'J2000',
    abcorr: 'LT+S',
    sampleWindow: { start: '2026-05-12T00:00:00Z', stop: '2026-05-13T00:00:00Z' },
    description: 'MRO spacecraft geometry over Mars with current reconstructed SPK coverage.',
    requiredRoles: ['leapseconds', 'body-constants', 'planetary-ephemeris', 'mars-system', 'spacecraft-trajectory'],
    optionalRoles: ['spacecraft-structure', 'frame-definition', 'instrument-definition', 'spacecraft-clock', 'attitude'],
    calculations: ['state-vector', 'range-rate', 'phase-angle', 'sub-observer-point', 'sub-solar-point'],
    tags: ['mission', 'mars', 'active'],
  },
  {
    id: 'cassini-enceladus-2012',
    name: 'Cassini Enceladus flyby window',
    mission: 'Cassini',
    observer: 'CASSINI',
    target: 'ENCELADUS',
    center: 'SATURN',
    frame: 'J2000',
    abcorr: 'LT+S',
    sampleWindow: { start: '2012-10-19T08:00:00Z', stop: '2012-10-19T10:00:00Z' },
    description: 'Archival Cassini geometry around an Enceladus encounter, useful for testing Saturn-system workflows.',
    requiredRoles: ['leapseconds', 'body-constants', 'planetary-ephemeris', 'saturn-system', 'spacecraft-trajectory'],
    optionalRoles: ['spacecraft-structure', 'frame-definition', 'instrument-definition', 'spacecraft-clock', 'attitude'],
    calculations: ['state-vector', 'range-rate', 'phase-angle', 'sub-observer-point', 'sub-solar-point'],
    tags: ['archive', 'saturn', 'flyby'],
  },
];

export function getScenario(id) {
  return SCENARIOS.find((s) => s.id === id);
}
