export function generateMetaKernel(kernels, title = 'spice-doctor scenario') {
  const lines = [
    'KPL/MK',
    '',
    '\\begintext',
    '',
    `Meta-kernel generated by spice-doctor for ${title}.`,
    'Download the listed kernels from NAIF and preserve the local paths below.',
    '',
    '\\begindata',
    '',
    "PATH_VALUES = ( 'kernels' )",
    "PATH_SYMBOLS = ( 'KERNELS' )",
    '',
    'KERNELS_TO_LOAD = (',
    ...kernels.map((kernel) => `  '$KERNELS/${kernel.localPath}'`),
    ')',
    '',
    '\\begintext',
    '',
  ];
  return lines.join('\n');
}

export function generateDownloadList(kernels) {
  return kernels.map((kernel) => `${kernel.url} -> kernels/${kernel.localPath}`).join('\n');
}

export function toJsonReport(report) {
  return JSON.stringify(
    {
      scenario: report.scenario,
      request: report.request,
      status: report.status,
      issues: report.issues,
      kernels: report.kernels,
      selections: report.selections,
      handoff: report.handoff
        ? {
            checklist: report.handoff.checklist,
            timeline: report.handoff.timeline,
            suggestions: report.handoff.suggestions,
          }
        : undefined,
    },
    null,
    2,
  );
}
